spring.application.name=users-demo

spring.datasource.url=jdbc:h2:mem:usersdb

spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info,loggers

springdoc.swagger-ui.url=/openapi.yaml
